name: build-pdf
on:
  push:
    branches: [ "main", "setup/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate QR codes
        run: python scripts/genera_qr.py
      - name: Build PDFs with Dockerized pandoc/latex
        run: bash scripts/build.sh
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: pdf-bundle
          path: build/pdf/
          if-no-files-found: error
